# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDBlOTJiZmYxYTI2YTFjMjkyZWQxYjFiY2E4YjRjYTVlMzU1NWFlY2Y2Y2U0Yzg5YWFiMDgxMzJmZDk5YmQzZGNlYzQyZTkxZGIwMmJkYzE3OWZjNjMyZjhjMDU4MTU1ODU1NzIyZGQyMDc2ODkwMjExOTE1OTc5OWFhMmZkNmE=
